name: Auto Booking

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 22 * * *'  # Каждый день в 00:00 по Madrid (22:00 UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y coreutils curl

      - name: Run script
        run: |
          chmod +x status1.sh
          ./status1.sh

